language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: T+VmPpT/SyfqGuA5tNbEiw+K7t7qTmCsp3CdBEd/V/CNbpfffLcH946G8vJP9xP5VRgBoD4woqrsoIPV7SKH5D2uZRiEqWSNYOowPWt1e5HjCw7gzlo3Q0xbdfetVuIbkGP8tT8zD+pByU1TYe+bZ7HZd9moUu2Wbw4Kh2iOOElC4bnivtbEibIahDscXw5uZAJtAXiXkc/orsCSajASoyWeeC+ceuUNS/5dEfBR2uNjwAobxYsQR7diw3Q+kPKoRSWVIKeEy4qJ3k0CjruE3chTroZ6xeZfR8h5oNriuHmNrqr9atNkyupL8L/HM474Nv41jHsrgJY2pzoDeQZ5yHJmYIOqbmEgd0AVIU1MBsZgbuQT/LYlH6Ye5n243Nv2Mcke/aEBU2TpYJd7Rtp3vIxAMQj52CCT9z0AFoVn0xTmRlzJgnTmPqj71LO9Llyy6Stk2MeQXyMc1j34xbafJb7Z7SobArZ84QWYnIj4i7sezqSm4WlGU8LE8B/0WGFYinYizQHYUzZWQzz/p7Kss6qPtGDUiyDdJItkjZ+w8jENFCPu7ROkuB9qWiGUa/U58/OVdlv6eE4m8/NggkNtKPi9BnZEuQvhPlpr58pVuBsGBllOWwfppuN2jAmKdzpiQxUSlF4TkqsA6v5ejzG2qyg7eRjsHPGogJaaMnV6DJ4=
  app: sleepy-ravine-11904
